### ISSUE TITLE
[Linux] Biff resource references are not correctly resolved

### ISSUE THREAD

**Issue by Argent77** [NearInfinityBrowser/NearInfinity#137]
Biff resource references in the `chitin.key` don't appear to be resolved correctly on Linux systems. Case-sensitivity of the filesystem doesn't matter.

How to repro: Run [DLC Merger](https://github.com/Argent77/A7-DlcMerger) on a BGEE game with SoD present as DLC archive.

Error log:
```
java.io.IOException: sod-dlc/Default.bif not found
	at org.infinity.resource.key.Keyfile.getBIFFFile(Keyfile.java:415)
	at org.infinity.resource.key.BIFFResourceEntry.getResourceBuffer(BIFFResourceEntry.java:226)
	at org.infinity.resource.key.ResourceEntry.getResourceBuffer(ResourceEntry.java:172)
	at org.infinity.resource.text.PlainTextResource.<init>(PlainTextResource.java:105)
	at org.infinity.util.Table2da.init(Table2da.java:108)
	at org.infinity.util.Table2da.<init>(Table2da.java:37)
	at org.infinity.util.Table2daCache.get(Table2daCache.java:51)
	at org.infinity.util.Table2daCache.get(Table2daCache.java:37)
	at org.infinity.resource.Profile.initCampaigns(Profile.java:2376)
	at org.infinity.resource.Profile.initFeatures(Profile.java:2368)
	at org.infinity.resource.Profile.initGame(Profile.java:1888)
	at org.infinity.resource.Profile.init(Profile.java:1681)
	at org.infinity.resource.Profile.<init>(Profile.java:1638)
	at org.infinity.resource.Profile.openGame(Profile.java:657)
	at org.infinity.NearInfinity$2.doInBackground(NearInfinity.java:346)
	at org.infinity.NearInfinity$2.doInBackground(NearInfinity.java:1)
	at javax.swing.SwingWorker$1.call(SwingWorker.java:295)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at javax.swing.SwingWorker.run(SwingWorker.java:334)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by lambda-dom** [comment]
Just in case it helps narrowing down the problem, I am *not* seeing this if I only use modmerge. A mod like generalized_biffing also seems to trigger the problem, so I suspect there is some weird interaction going with biffing operations.

**Comment by Argent77** [comment]
Yes, the issue is indirectly caused by WeiDU which by default lowercases all filenames on Linux. However, it should not have any impact on non-case-sensitive filesystems.

NI uses a custom routine to treat case-sensitive filesystems as non-case-sensitive internally. It looks like the responsible routine doesn't always work correctly though. I don't know yet when it can be fixed since I have to find a platform-independent way to query unix-specific filesystem attributes.

However, as a quick and dirty workaround I could probably add a command line parameter to the next NI release which forces all filename access as non-case-sensitive.

**Comment by lambda-dom** [comment]
Confirm that it works as of the latest version, by passing appropriate command line argument, e.g.:
`java -jar -/NearInfinity.jar -i`

**Comment by suy** [comment]
Can you elaborate on that command line argument? If I run with `java -jar NearInfinity-20210501.jar -i`, the GUI doesn't even show. If I run without the `-i` as usual, then it shows but tons of errors as reported.

I don't get what `-/NearInfinity.jar` is supposed be doing. I get an error on a wrong command line switch ("Unrecognized option: -/NearInfinity-20210501.jar").

**Comment by Argent77** [comment]
The `-i` option is just an interim solution (or hack) to fix file/folder access issues on non-case-sensitive filesystems on Linux. It basically disables case-detection, so that file access is handled just like on Windows or macOS. Don't use it if your filesystem is case-sensitive.

I'll have to rework the whole file manager used by NI internally to fix the issue properly.

**Comment by suy** [comment]
The thing is, that it doesn't seem to work for me (assuming I have to use it like I pasted above). Does it require some JVM version? Or it's an argument received by NearInfinity?

If I run it like that (with `-i`), I get:

```
java.nio.file.NoSuchFileException: /home/alex/local/GOG/bg2ee/ci-data-game/data/Patch2.bif
        at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
        at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:219)
        at java.base/java.nio.file.Files.newByteChannel(Files.java:371)
        at java.base/java.nio.file.Files.newByteChannel(Files.java:422)
        at java.base/java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:420)
        at java.base/java.nio.file.Files.newInputStream(Files.java:156)
        at org.infinity.util.io.StreamUtils.getInputStream(Unknown Source)
        at org.infinity.util.io.StreamUtils.getInputStream(Unknown Source)
        at org.infinity.resource.key.AbstractBIFFReader.detectBiffType(Unknown Source)
        at org.infinity.resource.key.AbstractBIFFReader.queryBIFFReader(Unknown Source)
        at org.infinity.resource.key.AbstractBIFFReader.open(Unknown Source)
        at org.infinity.resource.key.Keyfile.getBIFFFile(Unknown Source)
        at org.infinity.resource.key.BIFFResourceEntry.getResourceBuffer(Unknown Source)
        at org.infinity.resource.key.ResourceEntry.getResourceBuffer(Unknown Source)
        at org.infinity.resource.text.PlainTextResource.<init>(Unknown Source)
        at org.infinity.util.Table2da.init(Unknown Source)
        at org.infinity.util.Table2da.<init>(Unknown Source)
        at org.infinity.util.Table2daCache.get(Unknown Source)
        at org.infinity.util.Table2daCache.get(Unknown Source)
        at org.infinity.resource.Profile.initCampaigns(Unknown Source)
        at org.infinity.resource.Profile.initFeatures(Unknown Source)
        at org.infinity.resource.Profile.initGame(Unknown Source)
        at org.infinity.resource.Profile.init(Unknown Source)
        at org.infinity.resource.Profile.<init>(Unknown Source)
        at org.infinity.resource.Profile.openGame(Unknown Source)
        at org.infinity.NearInfinity$2.doInBackground(Unknown Source)
        at org.infinity.NearInfinity$2.doInBackground(Unknown Source)
        at java.desktop/javax.swing.SwingWorker$1.call(SwingWorker.java:304)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.desktop/javax.swing.SwingWorker.run(SwingWorker.java:343)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
```

Followed by a NullPointerException, then a crash which doesn't even show the UI.

If I instead call it *without* `-i`, I still get an error right away on the console, but at least it's just IO exceptions, and the GUI shows up. Then it's not too usable because there is a blocking dialog by just expanding the SPL, for example.

I've tried this on both a case sensitive and case insensitive installation directory. Old NearInfinity-20200901.jar works on both directories as well.

Let me know if I can give a hand in some way.

Thank you.

**Comment by Argent77** [comment]
Your trace log appears to list a couple more method calls. I can't reproduce it on my test machine.

Can you tell me more about the game installation?
- What filesystem are are you using?
- Did you modify the BG2EE game installation in some way (to-lower, mods, etc.)?

Could you also run the attached NI version and post the resulting debug log? It provides more useful debug information.

[NearInfinity-debug.zip](https://github.com/NearInfinityBrowser/NearInfinity/files/6411085/NearInfinity-debug.zip)

**Comment by lambda-dom** [comment]
> I don't get what `-/NearInfinity.jar` is supposed be doing. I get an error on a wrong command line switch ("Unrecognized option: -/NearInfinity-20210501.jar").

My bad. Replace "-" with ".". The rest is up with Argent77, but I stress that the problem has to do with using *case-insensitive* file systems on linux, that by default and contrary to Windows, uses *case-sensitive* file systems.

**Comment by lynxlynxlynx** [comment]
For me it works for an install on an ext4 partition (except our demo, which I'll report separately) and not on those on a ntfs one (mounted via fuse). They all worked before. If I try browsing CRE files it gives a popup error for each, so I have to kill it.

**Comment by Argent77** [comment]
> 
> For me it works for an install on an ext4 partition (except our demo, which I'll report separately) and not on those on a ntfs one (mounted via fuse). They all worked before. If I try browsing CRE files it gives a popup error for each, so I have to kill it.

Afaik, NTFS is case-preserving but not case-insensitive. That's why the workaround doesn't work.

I did a lot of clean up and refactoring recently, so maybe something else I/O-related broke in the process.

**Comment by suy** [comment]
The GOG installer that I use leaves a `game` directory which contains the root of the game (containing the chitin.key, etc.). Then I use `ciopfs` (FUSE-based "case insensitive on purpose FS") to have a case insensitive directory, by doing this:

```
# Move away the standard game directory
mv game game.original
# Create the dir that will contain the ciopfs data, which will contain additional
# case information in extended attributes ("user.filename")
mkdir ci-data-game/
# Recreate the game directory, and mount the empty data directory to it.
mkdir game
ciopfs ci-data-game/ game
# Copy the original game files. The case will be stored in the extended
# attributes.
cp -r game.original/* game
# Test that it worked by starting the game in the ciopfs mounted directory
cd game
./BaldursGate64
```

This ends up leaving:

1. The original game dir in `game.original`, as the GOG installer left it. I sometimes browse this to see how the unmodded game is.
2. The ciopfs "data" in `ci-data-game`, which are regular files created by ciopfs, all in lowercase but storing the "intended case" in extended attributes. This is fully usable, and when I use NearInfinity to browse the modded game, I point it to this directory to avoid having to worry about the performance hit of FUSE.
3. The mounted case insensitive directory in `game`. This is the one I need for playing after WeiDU. I don't even mount it for NearInfinity as it used to work on 2 just fine.

If I try with the `-i` flag in the case insensitive mount point, it seems to work without warnings in opening the game, but attempting to open anything ends up consuming the available file descriptors. It ends up throwing "java.nio.file.FileSystemException: .../game/data/Items.bif: Too many open files" and "java.io.IOException: Bad file descriptor".

I'm attaching the files of trying the debug version on the directories 2 and 3, with and without `-i`. The smaller file ("log-with-i+lowercase-real-fs.txt") corresponds to try to run NI, but it ends up crashing. The other bigger ones throw errors, but still I'm able to expand file types in the left tree. Passing `-i` and browsing the case insensitive mount point is not attached because it was empty till the "too many open files" error.

I tried to get the logs by just starting NI and letting it load the directory I wanted to try from the previously browsed game (that is, not choosing bookmarked games, etc.).

[log-with-i+lowercase-real-fs.txt](https://github.com/NearInfinityBrowser/NearInfinity/files/6411701/log-with-i%2Blowercase-real-fs.txt)
[log-without-i+case-insensitive-fuse-fs.txt](https://github.com/NearInfinityBrowser/NearInfinity/files/6411702/log-without-i%2Bcase-insensitive-fuse-fs.txt)
[log-without-i+lowercase-real-fs.txt](https://github.com/NearInfinityBrowser/NearInfinity/files/6411703/log-without-i%2Blowercase-real-fs.txt)

I'm not so sure the logs are being useful now... In order to prevent the crash I've started with an old NI (release 20200901) to be able to change the last recently used game, and in picking up the BG2EE from the FUSE case insensitive file system is also throwing the following:

[log-old-with-bg2ee-case-insensitive.txt](https://github.com/NearInfinityBrowser/NearInfinity/files/6411741/log-old-with-bg2ee-case-insensitive.txt)

**Comment by Argent77** [comment]
If I understand the concept of ciopfs correctly then the `ci-game` directory mirrors the data of the `game` directory, all in lower-case, with case information stored in their extended attributes.

In that case the `-i` parameter won't work since `ci-data` is still case-sensitive. You have to run NI with the `-i` option in the FUSE-mounted `game` directory to make use of the current workaround.

**Comment by suy** [comment]
Yes, your understanding is correct. And indeed, that seems to be the option that works better. Thank you for the help!

**Comment by lynxlynxlynx** [comment]
So, is there something we can do to help with this? Detecting case sensitivity is easy through temporary file creation.

**Comment by Argent77** [comment]
I haven't found the time to work on this issue yet.

I've used [a similar method](https://github.com/NearInfinityBrowser/NearInfinity/blob/355c1f25f0d17fd2580d5dc358718a11bf1250a9/src/org/infinity/util/io/FileManager.java#L597-L621) in the past. However, it didn't work reliably in more recent versions. Maybe the internal Java implementation changed or some of the recent changes in NI are to blame. In any case, I plan to overhaul the whole file manager class.

**Comment by Argent77** [comment]
That's probably what I'll do. However, since every game-related folder can potentially belong to a different partition/filesystem I would have to do lots of file checks. I'll probably just limit the checks to the game folder and the (EE-specific) user folder.

**Comment by lynxlynxlynx** [comment]
That's what the linked code is doing, just on a test file. It's true it's limited to /tmp, so it's not indicative of where the game is installed though.

**Comment by Argent77** [comment]
The linked code in my previous post demonstrated how I checked case-sensitivity in the past. It forwarded the actual case check to the internal Java class that handles filesystem calls and evaluates the result of the path comparison. That method isn't reliable anymore.

**Comment by Argent77** [comment]
Should be fixed by Argent77/NearInfinity@7084a29.

I have attached a precompiled Jar file for testing. Please report back if the problem persists, and I'll reopen the issue.

[NearInfinity-ci.zip](https://github.com/NearInfinityBrowser/NearInfinity/files/7455836/NearInfinity-ci.zip)

**Comment by suy** [comment]
Thanks for the patch. To me, this is still not a change in performance. When opening an unmodded game, expanding any file type on the tree is nearly instantaneous, while if there are overridden files, it takes many seconds and one CPU spikes.

**Comment by Argent77** [comment]
Do you have option `Show search names in resource tree` enabled? That option is quite time-consuming. It can be turned off in the Options menu.

Apart from that, checking existence of files in the override folder is a slow operation. I'll do some more test, maybe there's still room for improvements.

**Comment by suy** [comment]
I'll disable it for the time being. It still is strangely slow. Running `ls` on override takes about half a second on a real file system, and almost a second in a FUSE one (for the case insensitivity). I assume that if the speed difference is so huge in a modded vs unmodded game, is the presence of many files in override. In some installations, I just have the unmodded game with a few selected files overridden manually, and still the performance is good. It's when there are many that it plummets. Given that the tree needs to be refreshed for new files to be picked up, I assume the contents are in memory anyway, so it would have to be fast...

I'll try to find time to look into it as well. Thank you again.

**Comment by Argent77** [comment]
It's a Java-specific issue. NI uses the more recent `java.nio` packages for a while now, which provide many additional features over the older `java.io` packages. However, they can be slow as hell, sometimes.

**Comment by Argent77** [comment]
I did some more testing regarding the performance issue with override folder content. It's not worse on Linux than on other platforms. The loading time when NI is called for the first time can be significant if you have tens of thousands of files in the override folder. This is something I've been trying to optimize for years. It's less of an issue for subsequent calls of NI or when refreshing the resource tree content.

**Comment by suy** [comment]
Thank you. If it is the same everywhere, then it is what it is. :)
