### ISSUE TITLE
Feature request: CAB Export to gif

### ISSUE THREAD

**Issue by yjeroen** [NearInfinityBrowser/NearInfinity#144]
Would be amazing if we could extract an animated creature from the Creature Animation Browser to gif!

**Comment by Argent77** [comment]
Unfortunately the animated gif format is far too limited to support all features of creature animations. Since many animations consist of multiple layers the color count may exceed the gif palette limit. Moreover, these animations contain translucent colors as well as special blending effects which will be lost at export.

Other animated image formats may be more suitable (e.g. APNG or WebP). I'll see what I can do if I come across a suitable Java library for these formats.

**Comment by yjeroen** [comment]
APNG or animated WEBP would be even better of course. <3

**Comment by Argent77** [comment]
Experimental APNG export has been added for the next release: https://github.com/Argent77/NearInfinity/commit/6f47c416a9b51132d156091aef31e5b1e34890b7
