### ISSUE TITLE
Used up item incorrectly read in DAGG05.itm

### ISSUE THREAD

**Issue by suy** [NearInfinityBrowser/NearInfinity#181]
Hello.

I've noticed this very rare behavior when opening DAGG05.ITM from the vanilla Shadows of Amn. The "Used Up Item" is wrong. In the Edit tab, it displays "None". In the Raw viewer, the hex editor displays this:

![image](https://github.com/NearInfinityBrowser/NearInfinity/assets/1200609/f10350e1-45b6-4060-9a03-d8b6b3107737)

I've opened this with two other hex editors, and both display the string "item" instead (with 4 leading 0 bytes):

![image](https://github.com/NearInfinityBrowser/NearInfinity/assets/1200609/640c746d-8e84-48da-a721-20f212d76a95)

When reading the file with ieparse.py from iesh, it shows this:

```
Signature: ITM  
Version: V1   
Item name (generic): 6724 
Item name (identified): 6725 
Replacement item: item 
...
```

Doing a custom read, I get "\0\0\0\0item" instead, as the other hex editors showed.

I know it makes little sense to attempt to display something meaningful on the Edit tab, but the Raw one I expected it to be literally what the file is. I've seen that exporting the file doesn't corrupt it, and it produces the same file as `weidu --bif-get DAGG05.ITM` does.

Thank you!

**Comment by Argent77** [comment]
Resref strings are null-terminated. Since the first character is a `\0` character the whole resref string is considered empty. Any content after the first `\0` would be ignored by the engine. That's why it is cleaned up internally by NI, which also affects the Raw view (as well as the output of the "Save" operation.) Using the "Export" option preserves the original content, however.

The way how strings are parsed is probably as old as NI itself. I haven't changed this base behavior since there was no reason to change it. Doing so would probably require a more sophisticated implementation. But I can see your point of preserving the data even though it is unused. This is probably one of those problems where there is no clear "right" or "wrong" how to handle it.

**Comment by suy** [comment]
Thanks for the explanation. I was using NI to confirm my assumptions about files like ITM, and make a proper implementation of the format such that everything is preserved, including the many garbage strings that plenty of files have. I thought the Raw tab would be very preserving, but it makes sense that it's not 100% preserving if it needs to display there the details of what's an ability, what's an effect, etc, like it happens with Edit.

I'll close the issue, as with this information it makes sense how it works.

Thank you!
