### ISSUE TITLE
Scaled UI [Windows 10, high res monitor]

### ISSUE THREAD

**Issue by FredSRichardson** [NearInfinityBrowser/NearInfinity#81]
On a high resolution monitor the UI is too small.  It would be nice to have some way to scale it up for example on Windows 10.

**Comment by Argent77** [comment]
Java's Swing UI doesn't appear to support scalable controls. There is also no way to determine the monitor's DPI in Java. 

I may add a hack to increase font size for all UI controls, but that will have some undesired side effects, such as unaligned or cropped UI controls.

**Comment by FredSRichardson** [comment]
If the following can be believed:

http://superuser.com/questions/988379/how-do-i-run-java-apps-upscaled-on-a-high-dpi-display

Then there may be a work around to make the "DPI aware" flag work by
changing a manifest somewhere, but I can't tell if this is a manifest in
the Java install or in the JAR.  The flag that is supposed to work is:

-Dsun.java2d.dpiaware=false

See https://bugs.openjdk.java.net/browse/JDK-8080153 for more information
on the known bug in Java 8.

-Fred

**Comment by Argent77** [comment]
That doesn't look like a viable option since it involves placing a manifest file into the Java installation directory of the user which overrides the manifest included in the executable. It's also limited to Microsoft Windows.

Increasing the font size of UI controls in NI seems to work, though in a limited manner. There are some visual glitches like cropped text or controls that are still too small since they don't contain any text. I can fix some issues, but others require changes in the source code of Java itself. 
For now I don't want to implement something hackish like this. I can only hope that Oracle updates the Swing library to become DPI aware.

**Comment by FredSRichardson** [comment]
From this comment on the bug Java bug report, it looks like this will be
fixed in a future release of Java.  A short term fix for me is to hack my
Java install manifiest:

"I believe that we need to leave the dpiAvare=true option in the manifest
file for JDK 9 because JDK 9 is the DPI aware application. It reads DPI
settings from the OS system and scales the whole app accordingly to it"

**Comment by Argent77** [comment]
[This commit](https://github.com/Argent77/NearInfinity/commit/3b2ca1e1d4fb918cd24ead26b07eb708ecf3c452) adds scalable UI font sizes to NI, which hopefully increases usability on high DPI monitors.

**Comment by burner1024** [comment]
Argent's77 last release is working great with -Dsun.java2d.uiScale=2 on linux/openjdk 10

**Comment by Argent77** [comment]
The scalable UI font size option is now stable enough and should provide a good work-around for high dpi displays. Closing this issue.
