### ISSUE TITLE
Please help

### ISSUE THREAD

**Issue by Imiona** [NearInfinityBrowser/NearInfinity#82]
Hello

Can someone maybe tell me if its possible to Convert,Name and Output Multiple BMP's to BAM's at once with the build in Converter? I read the Documentation, something about splittet output, but i cant figure it out (i use this Tool for the very first Time). I would like to make a (massive) overhaul of all the Icons in BGEE (later IWDEE) with my Custom ones, and it would really really help and speed up the Process if this would be possible or added to the Tool :)

Thank you

Mikey

**Comment by Argent77** [comment]
NI's BAM Converter is designed to work on individual animations only. A batch processor wouldn't make much sense since BAM files can be configured in so many different ways. I would have to hardcode a handful use cases to make it work (to a limited extent).

Miloch's [BAM Batcher](http://www.shsforums.net/files/file/837-bam-batcher/) mod already does exactly what you have outlined in [your topic](http://gibberlings3.net/forums/index.php?showtopic=28306) on G3. You have to prepare the source material appropriately though (see the mod's readme for more details).

**Comment by Imiona** [comment]
Yeah i tryed the Batcher but i cant get it to work, getting an Error all  the Time, but no Matter, i do it the long and hard Way now :)

Thx
